/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
)

// checks if the SelectableIntegration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SelectableIntegration{}

// SelectableIntegration struct for SelectableIntegration
type SelectableIntegration struct {
	Id string `json:"id"`
}

// NewSelectableIntegration instantiates a new SelectableIntegration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSelectableIntegration(id string) *SelectableIntegration {
	this := SelectableIntegration{}
	this.Id = id
	return &this
}

// NewSelectableIntegrationWithDefaults instantiates a new SelectableIntegration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSelectableIntegrationWithDefaults() *SelectableIntegration {
	this := SelectableIntegration{}
	return &this
}

// GetId returns the Id field value
func (o *SelectableIntegration) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SelectableIntegration) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SelectableIntegration) SetId(v string) {
	o.Id = v
}

func (o SelectableIntegration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SelectableIntegration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableSelectableIntegration struct {
	value *SelectableIntegration
	isSet bool
}

func (v NullableSelectableIntegration) Get() *SelectableIntegration {
	return v.value
}

func (v *NullableSelectableIntegration) Set(val *SelectableIntegration) {
	v.value = val
	v.isSet = true
}

func (v NullableSelectableIntegration) IsSet() bool {
	return v.isSet
}

func (v *NullableSelectableIntegration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSelectableIntegration(val *SelectableIntegration) *NullableSelectableIntegration {
	return &NullableSelectableIntegration{value: val, isSet: true}
}

func (v NullableSelectableIntegration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSelectableIntegration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
