/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
)

// checks if the ConnectDetailsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectDetailsResponse{}

// ConnectDetailsResponse struct for ConnectDetailsResponse
type ConnectDetailsResponse struct {
	Details string `json:"details"`
}

// NewConnectDetailsResponse instantiates a new ConnectDetailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectDetailsResponse(details string) *ConnectDetailsResponse {
	this := ConnectDetailsResponse{}
	this.Details = details
	return &this
}

// NewConnectDetailsResponseWithDefaults instantiates a new ConnectDetailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectDetailsResponseWithDefaults() *ConnectDetailsResponse {
	this := ConnectDetailsResponse{}
	return &this
}

// GetDetails returns the Details field value
func (o *ConnectDetailsResponse) GetDetails() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *ConnectDetailsResponse) GetDetailsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *ConnectDetailsResponse) SetDetails(v string) {
	o.Details = v
}

func (o ConnectDetailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectDetailsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["details"] = o.Details
	return toSerialize, nil
}

type NullableConnectDetailsResponse struct {
	value *ConnectDetailsResponse
	isSet bool
}

func (v NullableConnectDetailsResponse) Get() *ConnectDetailsResponse {
	return v.value
}

func (v *NullableConnectDetailsResponse) Set(val *ConnectDetailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectDetailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectDetailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectDetailsResponse(val *ConnectDetailsResponse) *NullableConnectDetailsResponse {
	return &NullableConnectDetailsResponse{value: val, isSet: true}
}

func (v NullableConnectDetailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectDetailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
