/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
)

// checks if the AccessFlowModelV2Timeframe type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessFlowModelV2Timeframe{}

// AccessFlowModelV2Timeframe struct for AccessFlowModelV2Timeframe
type AccessFlowModelV2Timeframe struct {
	StartTimeSec int64       `json:"start_time_sec"`
	EndTimeSec   int64       `json:"end_time_sec"`
	DaysInWeek   []DayOfWeek `json:"days_in_week"`
	TimeZone     string      `json:"time_zone"`
}

// NewAccessFlowModelV2Timeframe instantiates a new AccessFlowModelV2Timeframe object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessFlowModelV2Timeframe(startTimeSec int64, endTimeSec int64, daysInWeek []DayOfWeek, timeZone string) *AccessFlowModelV2Timeframe {
	this := AccessFlowModelV2Timeframe{}
	this.StartTimeSec = startTimeSec
	this.EndTimeSec = endTimeSec
	this.DaysInWeek = daysInWeek
	this.TimeZone = timeZone
	return &this
}

// NewAccessFlowModelV2TimeframeWithDefaults instantiates a new AccessFlowModelV2Timeframe object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessFlowModelV2TimeframeWithDefaults() *AccessFlowModelV2Timeframe {
	this := AccessFlowModelV2Timeframe{}
	return &this
}

// GetStartTimeSec returns the StartTimeSec field value
func (o *AccessFlowModelV2Timeframe) GetStartTimeSec() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StartTimeSec
}

// GetStartTimeSecOk returns a tuple with the StartTimeSec field value
// and a boolean to check if the value has been set.
func (o *AccessFlowModelV2Timeframe) GetStartTimeSecOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTimeSec, true
}

// SetStartTimeSec sets field value
func (o *AccessFlowModelV2Timeframe) SetStartTimeSec(v int64) {
	o.StartTimeSec = v
}

// GetEndTimeSec returns the EndTimeSec field value
func (o *AccessFlowModelV2Timeframe) GetEndTimeSec() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EndTimeSec
}

// GetEndTimeSecOk returns a tuple with the EndTimeSec field value
// and a boolean to check if the value has been set.
func (o *AccessFlowModelV2Timeframe) GetEndTimeSecOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTimeSec, true
}

// SetEndTimeSec sets field value
func (o *AccessFlowModelV2Timeframe) SetEndTimeSec(v int64) {
	o.EndTimeSec = v
}

// GetDaysInWeek returns the DaysInWeek field value
func (o *AccessFlowModelV2Timeframe) GetDaysInWeek() []DayOfWeek {
	if o == nil {
		var ret []DayOfWeek
		return ret
	}

	return o.DaysInWeek
}

// GetDaysInWeekOk returns a tuple with the DaysInWeek field value
// and a boolean to check if the value has been set.
func (o *AccessFlowModelV2Timeframe) GetDaysInWeekOk() ([]DayOfWeek, bool) {
	if o == nil {
		return nil, false
	}
	return o.DaysInWeek, true
}

// SetDaysInWeek sets field value
func (o *AccessFlowModelV2Timeframe) SetDaysInWeek(v []DayOfWeek) {
	o.DaysInWeek = v
}

// GetTimeZone returns the TimeZone field value
func (o *AccessFlowModelV2Timeframe) GetTimeZone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value
// and a boolean to check if the value has been set.
func (o *AccessFlowModelV2Timeframe) GetTimeZoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeZone, true
}

// SetTimeZone sets field value
func (o *AccessFlowModelV2Timeframe) SetTimeZone(v string) {
	o.TimeZone = v
}

func (o AccessFlowModelV2Timeframe) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessFlowModelV2Timeframe) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start_time_sec"] = o.StartTimeSec
	toSerialize["end_time_sec"] = o.EndTimeSec
	toSerialize["days_in_week"] = o.DaysInWeek
	toSerialize["time_zone"] = o.TimeZone
	return toSerialize, nil
}

type NullableAccessFlowModelV2Timeframe struct {
	value *AccessFlowModelV2Timeframe
	isSet bool
}

func (v NullableAccessFlowModelV2Timeframe) Get() *AccessFlowModelV2Timeframe {
	return v.value
}

func (v *NullableAccessFlowModelV2Timeframe) Set(val *AccessFlowModelV2Timeframe) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessFlowModelV2Timeframe) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessFlowModelV2Timeframe) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessFlowModelV2Timeframe(val *AccessFlowModelV2Timeframe) *NullableAccessFlowModelV2Timeframe {
	return &NullableAccessFlowModelV2Timeframe{value: val, isSet: true}
}

func (v NullableAccessFlowModelV2Timeframe) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessFlowModelV2Timeframe) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
