/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
)

// checks if the AccessTargetModelV3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessTargetModelV3{}

// AccessTargetModelV3 struct for AccessTargetModelV3
type AccessTargetModelV3 struct {
	IntegrationId       string       `json:"integration_id"`
	ResourceType        string       `json:"resource_type"`
	ResourceTagMatchers []TagModelV3 `json:"resource_tag_matchers"`
	Permissions         []string     `json:"permissions"`
}

// NewAccessTargetModelV3 instantiates a new AccessTargetModelV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessTargetModelV3(integrationId string, resourceType string, resourceTagMatchers []TagModelV3, permissions []string) *AccessTargetModelV3 {
	this := AccessTargetModelV3{}
	this.IntegrationId = integrationId
	this.ResourceType = resourceType
	this.ResourceTagMatchers = resourceTagMatchers
	this.Permissions = permissions
	return &this
}

// NewAccessTargetModelV3WithDefaults instantiates a new AccessTargetModelV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessTargetModelV3WithDefaults() *AccessTargetModelV3 {
	this := AccessTargetModelV3{}
	return &this
}

// GetIntegrationId returns the IntegrationId field value
func (o *AccessTargetModelV3) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *AccessTargetModelV3) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *AccessTargetModelV3) SetIntegrationId(v string) {
	o.IntegrationId = v
}

// GetResourceType returns the ResourceType field value
func (o *AccessTargetModelV3) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *AccessTargetModelV3) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *AccessTargetModelV3) SetResourceType(v string) {
	o.ResourceType = v
}

// GetResourceTagMatchers returns the ResourceTagMatchers field value
func (o *AccessTargetModelV3) GetResourceTagMatchers() []TagModelV3 {
	if o == nil {
		var ret []TagModelV3
		return ret
	}

	return o.ResourceTagMatchers
}

// GetResourceTagMatchersOk returns a tuple with the ResourceTagMatchers field value
// and a boolean to check if the value has been set.
func (o *AccessTargetModelV3) GetResourceTagMatchersOk() ([]TagModelV3, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceTagMatchers, true
}

// SetResourceTagMatchers sets field value
func (o *AccessTargetModelV3) SetResourceTagMatchers(v []TagModelV3) {
	o.ResourceTagMatchers = v
}

// GetPermissions returns the Permissions field value
func (o *AccessTargetModelV3) GetPermissions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value
// and a boolean to check if the value has been set.
func (o *AccessTargetModelV3) GetPermissionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Permissions, true
}

// SetPermissions sets field value
func (o *AccessTargetModelV3) SetPermissions(v []string) {
	o.Permissions = v
}

func (o AccessTargetModelV3) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessTargetModelV3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["integration_id"] = o.IntegrationId
	toSerialize["resource_type"] = o.ResourceType
	toSerialize["resource_tag_matchers"] = o.ResourceTagMatchers
	toSerialize["permissions"] = o.Permissions
	return toSerialize, nil
}

type NullableAccessTargetModelV3 struct {
	value *AccessTargetModelV3
	isSet bool
}

func (v NullableAccessTargetModelV3) Get() *AccessTargetModelV3 {
	return v.value
}

func (v *NullableAccessTargetModelV3) Set(val *AccessTargetModelV3) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessTargetModelV3) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessTargetModelV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessTargetModelV3(val *AccessTargetModelV3) *NullableAccessTargetModelV3 {
	return &NullableAccessTargetModelV3{value: val, isSet: true}
}

func (v NullableAccessTargetModelV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessTargetModelV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
