/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
)

// checks if the ResourceV3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceV3{}

// ResourceV3 struct for ResourceV3
type ResourceV3 struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

// NewResourceV3 instantiates a new ResourceV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceV3(id string, name string, type_ string) *ResourceV3 {
	this := ResourceV3{}
	this.Id = id
	this.Name = name
	this.Type = type_
	return &this
}

// NewResourceV3WithDefaults instantiates a new ResourceV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceV3WithDefaults() *ResourceV3 {
	this := ResourceV3{}
	return &this
}

// GetId returns the Id field value
func (o *ResourceV3) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ResourceV3) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ResourceV3) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ResourceV3) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ResourceV3) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ResourceV3) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *ResourceV3) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ResourceV3) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ResourceV3) SetType(v string) {
	o.Type = v
}

func (o ResourceV3) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceV3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableResourceV3 struct {
	value *ResourceV3
	isSet bool
}

func (v NullableResourceV3) Get() *ResourceV3 {
	return v.value
}

func (v *NullableResourceV3) Set(val *ResourceV3) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceV3) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceV3(val *ResourceV3) *NullableResourceV3 {
	return &NullableResourceV3{value: val, isSet: true}
}

func (v NullableResourceV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
