/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
)

// checks if the PaginatedResponseIdentityModelV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseIdentityModelV2{}

// PaginatedResponseIdentityModelV2 struct for PaginatedResponseIdentityModelV2
type PaginatedResponseIdentityModelV2 struct {
	Data       []IdentityModel2 `json:"data"`
	Pagination PaginationInfo   `json:"pagination"`
}

// NewPaginatedResponseIdentityModelV2 instantiates a new PaginatedResponseIdentityModelV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseIdentityModelV2(data []IdentityModel2, pagination PaginationInfo) *PaginatedResponseIdentityModelV2 {
	this := PaginatedResponseIdentityModelV2{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewPaginatedResponseIdentityModelV2WithDefaults instantiates a new PaginatedResponseIdentityModelV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseIdentityModelV2WithDefaults() *PaginatedResponseIdentityModelV2 {
	this := PaginatedResponseIdentityModelV2{}
	return &this
}

// GetData returns the Data field value
func (o *PaginatedResponseIdentityModelV2) GetData() []IdentityModel2 {
	if o == nil {
		var ret []IdentityModel2
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseIdentityModelV2) GetDataOk() ([]IdentityModel2, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PaginatedResponseIdentityModelV2) SetData(v []IdentityModel2) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *PaginatedResponseIdentityModelV2) GetPagination() PaginationInfo {
	if o == nil {
		var ret PaginationInfo
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseIdentityModelV2) GetPaginationOk() (*PaginationInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedResponseIdentityModelV2) SetPagination(v PaginationInfo) {
	o.Pagination = v
}

func (o PaginatedResponseIdentityModelV2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResponseIdentityModelV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

type NullablePaginatedResponseIdentityModelV2 struct {
	value *PaginatedResponseIdentityModelV2
	isSet bool
}

func (v NullablePaginatedResponseIdentityModelV2) Get() *PaginatedResponseIdentityModelV2 {
	return v.value
}

func (v *NullablePaginatedResponseIdentityModelV2) Set(val *PaginatedResponseIdentityModelV2) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseIdentityModelV2) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseIdentityModelV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseIdentityModelV2(val *PaginatedResponseIdentityModelV2) *NullablePaginatedResponseIdentityModelV2 {
	return &NullablePaginatedResponseIdentityModelV2{value: val, isSet: true}
}

func (v NullablePaginatedResponseIdentityModelV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseIdentityModelV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
