/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
)

// checks if the GranteeModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GranteeModel{}

// GranteeModel struct for GranteeModel
type GranteeModel struct {
	Id   string           `json:"id"`
	Type GranteeTypeModel `json:"type"`
}

// NewGranteeModel instantiates a new GranteeModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGranteeModel(id string, type_ GranteeTypeModel) *GranteeModel {
	this := GranteeModel{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewGranteeModelWithDefaults instantiates a new GranteeModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGranteeModelWithDefaults() *GranteeModel {
	this := GranteeModel{}
	return &this
}

// GetId returns the Id field value
func (o *GranteeModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GranteeModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GranteeModel) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *GranteeModel) GetType() GranteeTypeModel {
	if o == nil {
		var ret GranteeTypeModel
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GranteeModel) GetTypeOk() (*GranteeTypeModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GranteeModel) SetType(v GranteeTypeModel) {
	o.Type = v
}

func (o GranteeModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GranteeModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableGranteeModel struct {
	value *GranteeModel
	isSet bool
}

func (v NullableGranteeModel) Get() *GranteeModel {
	return v.value
}

func (v *NullableGranteeModel) Set(val *GranteeModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGranteeModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGranteeModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGranteeModel(val *GranteeModel) *NullableGranteeModel {
	return &NullableGranteeModel{value: val, isSet: true}
}

func (v NullableGranteeModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGranteeModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
