/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
)

// checks if the CreateAccessFlowRequestV3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccessFlowRequestV3{}

// CreateAccessFlowRequestV3 struct for CreateAccessFlowRequestV3
type CreateAccessFlowRequestV3 struct {
	Name                  string                             `json:"name"`
	Active                bool                               `json:"active"`
	TriggerType           TriggerType                        `json:"trigger_type"`
	Grantees              []GranteeModel                     `json:"grantees"`
	AccessTargets         []AccessTargetModelV3              `json:"access_targets"`
	Approvers             []ApproverModel                    `json:"approvers"`
	RequireAllApprovers   NullableBool                       `json:"require_all_approvers,omitempty"`
	RevokeAfterInSec      int32                              `json:"revoke_after_in_sec"`
	JustificationRequired bool                               `json:"justification_required"`
	Timeframe             NullableAccessFlowModelV3Timeframe `json:"timeframe,omitempty"`
}

// NewCreateAccessFlowRequestV3 instantiates a new CreateAccessFlowRequestV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccessFlowRequestV3(name string, active bool, triggerType TriggerType, grantees []GranteeModel, accessTargets []AccessTargetModelV3, approvers []ApproverModel, revokeAfterInSec int32, justificationRequired bool) *CreateAccessFlowRequestV3 {
	this := CreateAccessFlowRequestV3{}
	this.Name = name
	this.Active = active
	this.TriggerType = triggerType
	this.Grantees = grantees
	this.AccessTargets = accessTargets
	this.Approvers = approvers
	this.RevokeAfterInSec = revokeAfterInSec
	this.JustificationRequired = justificationRequired
	return &this
}

// NewCreateAccessFlowRequestV3WithDefaults instantiates a new CreateAccessFlowRequestV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccessFlowRequestV3WithDefaults() *CreateAccessFlowRequestV3 {
	this := CreateAccessFlowRequestV3{}
	return &this
}

// GetName returns the Name field value
func (o *CreateAccessFlowRequestV3) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAccessFlowRequestV3) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAccessFlowRequestV3) SetName(v string) {
	o.Name = v
}

// GetActive returns the Active field value
func (o *CreateAccessFlowRequestV3) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *CreateAccessFlowRequestV3) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *CreateAccessFlowRequestV3) SetActive(v bool) {
	o.Active = v
}

// GetTriggerType returns the TriggerType field value
func (o *CreateAccessFlowRequestV3) GetTriggerType() TriggerType {
	if o == nil {
		var ret TriggerType
		return ret
	}

	return o.TriggerType
}

// GetTriggerTypeOk returns a tuple with the TriggerType field value
// and a boolean to check if the value has been set.
func (o *CreateAccessFlowRequestV3) GetTriggerTypeOk() (*TriggerType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TriggerType, true
}

// SetTriggerType sets field value
func (o *CreateAccessFlowRequestV3) SetTriggerType(v TriggerType) {
	o.TriggerType = v
}

// GetGrantees returns the Grantees field value
func (o *CreateAccessFlowRequestV3) GetGrantees() []GranteeModel {
	if o == nil {
		var ret []GranteeModel
		return ret
	}

	return o.Grantees
}

// GetGranteesOk returns a tuple with the Grantees field value
// and a boolean to check if the value has been set.
func (o *CreateAccessFlowRequestV3) GetGranteesOk() ([]GranteeModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Grantees, true
}

// SetGrantees sets field value
func (o *CreateAccessFlowRequestV3) SetGrantees(v []GranteeModel) {
	o.Grantees = v
}

// GetAccessTargets returns the AccessTargets field value
func (o *CreateAccessFlowRequestV3) GetAccessTargets() []AccessTargetModelV3 {
	if o == nil {
		var ret []AccessTargetModelV3
		return ret
	}

	return o.AccessTargets
}

// GetAccessTargetsOk returns a tuple with the AccessTargets field value
// and a boolean to check if the value has been set.
func (o *CreateAccessFlowRequestV3) GetAccessTargetsOk() ([]AccessTargetModelV3, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccessTargets, true
}

// SetAccessTargets sets field value
func (o *CreateAccessFlowRequestV3) SetAccessTargets(v []AccessTargetModelV3) {
	o.AccessTargets = v
}

// GetApprovers returns the Approvers field value
func (o *CreateAccessFlowRequestV3) GetApprovers() []ApproverModel {
	if o == nil {
		var ret []ApproverModel
		return ret
	}

	return o.Approvers
}

// GetApproversOk returns a tuple with the Approvers field value
// and a boolean to check if the value has been set.
func (o *CreateAccessFlowRequestV3) GetApproversOk() ([]ApproverModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Approvers, true
}

// SetApprovers sets field value
func (o *CreateAccessFlowRequestV3) SetApprovers(v []ApproverModel) {
	o.Approvers = v
}

// GetRequireAllApprovers returns the RequireAllApprovers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAccessFlowRequestV3) GetRequireAllApprovers() bool {
	if o == nil || IsNil(o.RequireAllApprovers.Get()) {
		var ret bool
		return ret
	}
	return *o.RequireAllApprovers.Get()
}

// GetRequireAllApproversOk returns a tuple with the RequireAllApprovers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAccessFlowRequestV3) GetRequireAllApproversOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequireAllApprovers.Get(), o.RequireAllApprovers.IsSet()
}

// HasRequireAllApprovers returns a boolean if a field has been set.
func (o *CreateAccessFlowRequestV3) HasRequireAllApprovers() bool {
	if o != nil && o.RequireAllApprovers.IsSet() {
		return true
	}

	return false
}

// SetRequireAllApprovers gets a reference to the given NullableBool and assigns it to the RequireAllApprovers field.
func (o *CreateAccessFlowRequestV3) SetRequireAllApprovers(v bool) {
	o.RequireAllApprovers.Set(&v)
}

// SetRequireAllApproversNil sets the value for RequireAllApprovers to be an explicit nil
func (o *CreateAccessFlowRequestV3) SetRequireAllApproversNil() {
	o.RequireAllApprovers.Set(nil)
}

// UnsetRequireAllApprovers ensures that no value is present for RequireAllApprovers, not even an explicit nil
func (o *CreateAccessFlowRequestV3) UnsetRequireAllApprovers() {
	o.RequireAllApprovers.Unset()
}

// GetRevokeAfterInSec returns the RevokeAfterInSec field value
func (o *CreateAccessFlowRequestV3) GetRevokeAfterInSec() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RevokeAfterInSec
}

// GetRevokeAfterInSecOk returns a tuple with the RevokeAfterInSec field value
// and a boolean to check if the value has been set.
func (o *CreateAccessFlowRequestV3) GetRevokeAfterInSecOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RevokeAfterInSec, true
}

// SetRevokeAfterInSec sets field value
func (o *CreateAccessFlowRequestV3) SetRevokeAfterInSec(v int32) {
	o.RevokeAfterInSec = v
}

// GetJustificationRequired returns the JustificationRequired field value
func (o *CreateAccessFlowRequestV3) GetJustificationRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.JustificationRequired
}

// GetJustificationRequiredOk returns a tuple with the JustificationRequired field value
// and a boolean to check if the value has been set.
func (o *CreateAccessFlowRequestV3) GetJustificationRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JustificationRequired, true
}

// SetJustificationRequired sets field value
func (o *CreateAccessFlowRequestV3) SetJustificationRequired(v bool) {
	o.JustificationRequired = v
}

// GetTimeframe returns the Timeframe field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAccessFlowRequestV3) GetTimeframe() AccessFlowModelV3Timeframe {
	if o == nil || IsNil(o.Timeframe.Get()) {
		var ret AccessFlowModelV3Timeframe
		return ret
	}
	return *o.Timeframe.Get()
}

// GetTimeframeOk returns a tuple with the Timeframe field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAccessFlowRequestV3) GetTimeframeOk() (*AccessFlowModelV3Timeframe, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeframe.Get(), o.Timeframe.IsSet()
}

// HasTimeframe returns a boolean if a field has been set.
func (o *CreateAccessFlowRequestV3) HasTimeframe() bool {
	if o != nil && o.Timeframe.IsSet() {
		return true
	}

	return false
}

// SetTimeframe gets a reference to the given NullableAccessFlowModelV3Timeframe and assigns it to the Timeframe field.
func (o *CreateAccessFlowRequestV3) SetTimeframe(v AccessFlowModelV3Timeframe) {
	o.Timeframe.Set(&v)
}

// SetTimeframeNil sets the value for Timeframe to be an explicit nil
func (o *CreateAccessFlowRequestV3) SetTimeframeNil() {
	o.Timeframe.Set(nil)
}

// UnsetTimeframe ensures that no value is present for Timeframe, not even an explicit nil
func (o *CreateAccessFlowRequestV3) UnsetTimeframe() {
	o.Timeframe.Unset()
}

func (o CreateAccessFlowRequestV3) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccessFlowRequestV3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["active"] = o.Active
	toSerialize["trigger_type"] = o.TriggerType
	toSerialize["grantees"] = o.Grantees
	toSerialize["access_targets"] = o.AccessTargets
	toSerialize["approvers"] = o.Approvers
	if o.RequireAllApprovers.IsSet() {
		toSerialize["require_all_approvers"] = o.RequireAllApprovers.Get()
	}
	toSerialize["revoke_after_in_sec"] = o.RevokeAfterInSec
	toSerialize["justification_required"] = o.JustificationRequired
	if o.Timeframe.IsSet() {
		toSerialize["timeframe"] = o.Timeframe.Get()
	}
	return toSerialize, nil
}

type NullableCreateAccessFlowRequestV3 struct {
	value *CreateAccessFlowRequestV3
	isSet bool
}

func (v NullableCreateAccessFlowRequestV3) Get() *CreateAccessFlowRequestV3 {
	return v.value
}

func (v *NullableCreateAccessFlowRequestV3) Set(val *CreateAccessFlowRequestV3) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccessFlowRequestV3) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccessFlowRequestV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccessFlowRequestV3(val *CreateAccessFlowRequestV3) *NullableCreateAccessFlowRequestV3 {
	return &NullableCreateAccessFlowRequestV3{value: val, isSet: true}
}

func (v NullableCreateAccessFlowRequestV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccessFlowRequestV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
