/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
)

// checks if the AccessFlowTriggerV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessFlowTriggerV1{}

// AccessFlowTriggerV1 struct for AccessFlowTriggerV1
type AccessFlowTriggerV1 struct {
	Type      string                               `json:"type"`
	Timeframe NullableAccessFlowTriggerV1Timeframe `json:"timeframe,omitempty"`
}

// NewAccessFlowTriggerV1 instantiates a new AccessFlowTriggerV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessFlowTriggerV1(type_ string) *AccessFlowTriggerV1 {
	this := AccessFlowTriggerV1{}
	this.Type = type_
	return &this
}

// NewAccessFlowTriggerV1WithDefaults instantiates a new AccessFlowTriggerV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessFlowTriggerV1WithDefaults() *AccessFlowTriggerV1 {
	this := AccessFlowTriggerV1{}
	return &this
}

// GetType returns the Type field value
func (o *AccessFlowTriggerV1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AccessFlowTriggerV1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AccessFlowTriggerV1) SetType(v string) {
	o.Type = v
}

// GetTimeframe returns the Timeframe field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccessFlowTriggerV1) GetTimeframe() AccessFlowTriggerV1Timeframe {
	if o == nil || IsNil(o.Timeframe.Get()) {
		var ret AccessFlowTriggerV1Timeframe
		return ret
	}
	return *o.Timeframe.Get()
}

// GetTimeframeOk returns a tuple with the Timeframe field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccessFlowTriggerV1) GetTimeframeOk() (*AccessFlowTriggerV1Timeframe, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeframe.Get(), o.Timeframe.IsSet()
}

// HasTimeframe returns a boolean if a field has been set.
func (o *AccessFlowTriggerV1) HasTimeframe() bool {
	if o != nil && o.Timeframe.IsSet() {
		return true
	}

	return false
}

// SetTimeframe gets a reference to the given NullableAccessFlowTriggerV1Timeframe and assigns it to the Timeframe field.
func (o *AccessFlowTriggerV1) SetTimeframe(v AccessFlowTriggerV1Timeframe) {
	o.Timeframe.Set(&v)
}

// SetTimeframeNil sets the value for Timeframe to be an explicit nil
func (o *AccessFlowTriggerV1) SetTimeframeNil() {
	o.Timeframe.Set(nil)
}

// UnsetTimeframe ensures that no value is present for Timeframe, not even an explicit nil
func (o *AccessFlowTriggerV1) UnsetTimeframe() {
	o.Timeframe.Unset()
}

func (o AccessFlowTriggerV1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessFlowTriggerV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if o.Timeframe.IsSet() {
		toSerialize["timeframe"] = o.Timeframe.Get()
	}
	return toSerialize, nil
}

type NullableAccessFlowTriggerV1 struct {
	value *AccessFlowTriggerV1
	isSet bool
}

func (v NullableAccessFlowTriggerV1) Get() *AccessFlowTriggerV1 {
	return v.value
}

func (v *NullableAccessFlowTriggerV1) Set(val *AccessFlowTriggerV1) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessFlowTriggerV1) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessFlowTriggerV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessFlowTriggerV1(val *AccessFlowTriggerV1) *NullableAccessFlowTriggerV1 {
	return &NullableAccessFlowTriggerV1{value: val, isSet: true}
}

func (v NullableAccessFlowTriggerV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessFlowTriggerV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
