/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
)

// checks if the UpdateAccessFlowModelV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAccessFlowModelV2{}

// UpdateAccessFlowModelV2 struct for UpdateAccessFlowModelV2
type UpdateAccessFlowModelV2 struct {
	Name                  string                             `json:"name"`
	Active                bool                               `json:"active"`
	TriggerType           TriggerType                        `json:"trigger_type"`
	Grantees              []GranteeModel                     `json:"grantees"`
	AccessTargets         []AccessTargetModel                `json:"access_targets"`
	Approvers             []ApproverModel                    `json:"approvers"`
	RevokeAfterInSec      int32                              `json:"revoke_after_in_sec"`
	JustificationRequired bool                               `json:"justification_required"`
	Timeframe             NullableAccessFlowModelV2Timeframe `json:"timeframe,omitempty"`
}

// NewUpdateAccessFlowModelV2 instantiates a new UpdateAccessFlowModelV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAccessFlowModelV2(name string, active bool, triggerType TriggerType, grantees []GranteeModel, accessTargets []AccessTargetModel, approvers []ApproverModel, revokeAfterInSec int32, justificationRequired bool) *UpdateAccessFlowModelV2 {
	this := UpdateAccessFlowModelV2{}
	this.Name = name
	this.Active = active
	this.TriggerType = triggerType
	this.Grantees = grantees
	this.AccessTargets = accessTargets
	this.Approvers = approvers
	this.RevokeAfterInSec = revokeAfterInSec
	this.JustificationRequired = justificationRequired
	return &this
}

// NewUpdateAccessFlowModelV2WithDefaults instantiates a new UpdateAccessFlowModelV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAccessFlowModelV2WithDefaults() *UpdateAccessFlowModelV2 {
	this := UpdateAccessFlowModelV2{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateAccessFlowModelV2) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateAccessFlowModelV2) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateAccessFlowModelV2) SetName(v string) {
	o.Name = v
}

// GetActive returns the Active field value
func (o *UpdateAccessFlowModelV2) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *UpdateAccessFlowModelV2) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *UpdateAccessFlowModelV2) SetActive(v bool) {
	o.Active = v
}

// GetTriggerType returns the TriggerType field value
func (o *UpdateAccessFlowModelV2) GetTriggerType() TriggerType {
	if o == nil {
		var ret TriggerType
		return ret
	}

	return o.TriggerType
}

// GetTriggerTypeOk returns a tuple with the TriggerType field value
// and a boolean to check if the value has been set.
func (o *UpdateAccessFlowModelV2) GetTriggerTypeOk() (*TriggerType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TriggerType, true
}

// SetTriggerType sets field value
func (o *UpdateAccessFlowModelV2) SetTriggerType(v TriggerType) {
	o.TriggerType = v
}

// GetGrantees returns the Grantees field value
func (o *UpdateAccessFlowModelV2) GetGrantees() []GranteeModel {
	if o == nil {
		var ret []GranteeModel
		return ret
	}

	return o.Grantees
}

// GetGranteesOk returns a tuple with the Grantees field value
// and a boolean to check if the value has been set.
func (o *UpdateAccessFlowModelV2) GetGranteesOk() ([]GranteeModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Grantees, true
}

// SetGrantees sets field value
func (o *UpdateAccessFlowModelV2) SetGrantees(v []GranteeModel) {
	o.Grantees = v
}

// GetAccessTargets returns the AccessTargets field value
func (o *UpdateAccessFlowModelV2) GetAccessTargets() []AccessTargetModel {
	if o == nil {
		var ret []AccessTargetModel
		return ret
	}

	return o.AccessTargets
}

// GetAccessTargetsOk returns a tuple with the AccessTargets field value
// and a boolean to check if the value has been set.
func (o *UpdateAccessFlowModelV2) GetAccessTargetsOk() ([]AccessTargetModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccessTargets, true
}

// SetAccessTargets sets field value
func (o *UpdateAccessFlowModelV2) SetAccessTargets(v []AccessTargetModel) {
	o.AccessTargets = v
}

// GetApprovers returns the Approvers field value
func (o *UpdateAccessFlowModelV2) GetApprovers() []ApproverModel {
	if o == nil {
		var ret []ApproverModel
		return ret
	}

	return o.Approvers
}

// GetApproversOk returns a tuple with the Approvers field value
// and a boolean to check if the value has been set.
func (o *UpdateAccessFlowModelV2) GetApproversOk() ([]ApproverModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Approvers, true
}

// SetApprovers sets field value
func (o *UpdateAccessFlowModelV2) SetApprovers(v []ApproverModel) {
	o.Approvers = v
}

// GetRevokeAfterInSec returns the RevokeAfterInSec field value
func (o *UpdateAccessFlowModelV2) GetRevokeAfterInSec() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RevokeAfterInSec
}

// GetRevokeAfterInSecOk returns a tuple with the RevokeAfterInSec field value
// and a boolean to check if the value has been set.
func (o *UpdateAccessFlowModelV2) GetRevokeAfterInSecOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RevokeAfterInSec, true
}

// SetRevokeAfterInSec sets field value
func (o *UpdateAccessFlowModelV2) SetRevokeAfterInSec(v int32) {
	o.RevokeAfterInSec = v
}

// GetJustificationRequired returns the JustificationRequired field value
func (o *UpdateAccessFlowModelV2) GetJustificationRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.JustificationRequired
}

// GetJustificationRequiredOk returns a tuple with the JustificationRequired field value
// and a boolean to check if the value has been set.
func (o *UpdateAccessFlowModelV2) GetJustificationRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JustificationRequired, true
}

// SetJustificationRequired sets field value
func (o *UpdateAccessFlowModelV2) SetJustificationRequired(v bool) {
	o.JustificationRequired = v
}

// GetTimeframe returns the Timeframe field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAccessFlowModelV2) GetTimeframe() AccessFlowModelV2Timeframe {
	if o == nil || IsNil(o.Timeframe.Get()) {
		var ret AccessFlowModelV2Timeframe
		return ret
	}
	return *o.Timeframe.Get()
}

// GetTimeframeOk returns a tuple with the Timeframe field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAccessFlowModelV2) GetTimeframeOk() (*AccessFlowModelV2Timeframe, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeframe.Get(), o.Timeframe.IsSet()
}

// HasTimeframe returns a boolean if a field has been set.
func (o *UpdateAccessFlowModelV2) HasTimeframe() bool {
	if o != nil && o.Timeframe.IsSet() {
		return true
	}

	return false
}

// SetTimeframe gets a reference to the given NullableAccessFlowModelV2Timeframe and assigns it to the Timeframe field.
func (o *UpdateAccessFlowModelV2) SetTimeframe(v AccessFlowModelV2Timeframe) {
	o.Timeframe.Set(&v)
}

// SetTimeframeNil sets the value for Timeframe to be an explicit nil
func (o *UpdateAccessFlowModelV2) SetTimeframeNil() {
	o.Timeframe.Set(nil)
}

// UnsetTimeframe ensures that no value is present for Timeframe, not even an explicit nil
func (o *UpdateAccessFlowModelV2) UnsetTimeframe() {
	o.Timeframe.Unset()
}

func (o UpdateAccessFlowModelV2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAccessFlowModelV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["active"] = o.Active
	toSerialize["trigger_type"] = o.TriggerType
	toSerialize["grantees"] = o.Grantees
	toSerialize["access_targets"] = o.AccessTargets
	toSerialize["approvers"] = o.Approvers
	toSerialize["revoke_after_in_sec"] = o.RevokeAfterInSec
	toSerialize["justification_required"] = o.JustificationRequired
	if o.Timeframe.IsSet() {
		toSerialize["timeframe"] = o.Timeframe.Get()
	}
	return toSerialize, nil
}

type NullableUpdateAccessFlowModelV2 struct {
	value *UpdateAccessFlowModelV2
	isSet bool
}

func (v NullableUpdateAccessFlowModelV2) Get() *UpdateAccessFlowModelV2 {
	return v.value
}

func (v *NullableUpdateAccessFlowModelV2) Set(val *UpdateAccessFlowModelV2) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAccessFlowModelV2) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAccessFlowModelV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAccessFlowModelV2(val *UpdateAccessFlowModelV2) *NullableUpdateAccessFlowModelV2 {
	return &NullableUpdateAccessFlowModelV2{value: val, isSet: true}
}

func (v NullableUpdateAccessFlowModelV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAccessFlowModelV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
