/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
)

// checks if the PaginatedAccessFlowSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedAccessFlowSearchResponse{}

// PaginatedAccessFlowSearchResponse struct for PaginatedAccessFlowSearchResponse
type PaginatedAccessFlowSearchResponse struct {
	Data         []AccessFlowModelV2      `json:"data"`
	FilterResult []AccessFlowFilterResult `json:"filter_result,omitempty"`
}

// NewPaginatedAccessFlowSearchResponse instantiates a new PaginatedAccessFlowSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedAccessFlowSearchResponse(data []AccessFlowModelV2) *PaginatedAccessFlowSearchResponse {
	this := PaginatedAccessFlowSearchResponse{}
	this.Data = data
	return &this
}

// NewPaginatedAccessFlowSearchResponseWithDefaults instantiates a new PaginatedAccessFlowSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedAccessFlowSearchResponseWithDefaults() *PaginatedAccessFlowSearchResponse {
	this := PaginatedAccessFlowSearchResponse{}
	return &this
}

// GetData returns the Data field value
func (o *PaginatedAccessFlowSearchResponse) GetData() []AccessFlowModelV2 {
	if o == nil {
		var ret []AccessFlowModelV2
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PaginatedAccessFlowSearchResponse) GetDataOk() ([]AccessFlowModelV2, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PaginatedAccessFlowSearchResponse) SetData(v []AccessFlowModelV2) {
	o.Data = v
}

// GetFilterResult returns the FilterResult field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedAccessFlowSearchResponse) GetFilterResult() []AccessFlowFilterResult {
	if o == nil {
		var ret []AccessFlowFilterResult
		return ret
	}
	return o.FilterResult
}

// GetFilterResultOk returns a tuple with the FilterResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedAccessFlowSearchResponse) GetFilterResultOk() ([]AccessFlowFilterResult, bool) {
	if o == nil || IsNil(o.FilterResult) {
		return nil, false
	}
	return o.FilterResult, true
}

// HasFilterResult returns a boolean if a field has been set.
func (o *PaginatedAccessFlowSearchResponse) HasFilterResult() bool {
	if o != nil && IsNil(o.FilterResult) {
		return true
	}

	return false
}

// SetFilterResult gets a reference to the given []AccessFlowFilterResult and assigns it to the FilterResult field.
func (o *PaginatedAccessFlowSearchResponse) SetFilterResult(v []AccessFlowFilterResult) {
	o.FilterResult = v
}

func (o PaginatedAccessFlowSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedAccessFlowSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if o.FilterResult != nil {
		toSerialize["filter_result"] = o.FilterResult
	}
	return toSerialize, nil
}

type NullablePaginatedAccessFlowSearchResponse struct {
	value *PaginatedAccessFlowSearchResponse
	isSet bool
}

func (v NullablePaginatedAccessFlowSearchResponse) Get() *PaginatedAccessFlowSearchResponse {
	return v.value
}

func (v *NullablePaginatedAccessFlowSearchResponse) Set(val *PaginatedAccessFlowSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedAccessFlowSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedAccessFlowSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedAccessFlowSearchResponse(val *PaginatedAccessFlowSearchResponse) *NullablePaginatedAccessFlowSearchResponse {
	return &NullablePaginatedAccessFlowSearchResponse{value: val, isSet: true}
}

func (v NullablePaginatedAccessFlowSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedAccessFlowSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
