/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateAccessRequestClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccessRequestClientModel{}

// CreateAccessRequestClientModel struct for CreateAccessRequestClientModel
type CreateAccessRequestClientModel struct {
	FilterIntegrationIds  []string      `json:"filter_integration_ids"`
	FilterBundleIds       []string      `json:"filter_bundle_ids"`
	FilterResourceTypeIds []string      `json:"filter_resource_type_ids"`
	FilterResourceIds     []string      `json:"filter_resource_ids"`
	FilterPermissionIds   []string      `json:"filter_permission_ids"`
	FilterAccessUnitIds   []string      `json:"filter_access_unit_ids"`
	Justification         string        `json:"justification"`
	Duration              NullableInt64 `json:"duration,omitempty"`
}

type _CreateAccessRequestClientModel CreateAccessRequestClientModel

// NewCreateAccessRequestClientModel instantiates a new CreateAccessRequestClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccessRequestClientModel(filterIntegrationIds []string, filterBundleIds []string, filterResourceTypeIds []string, filterResourceIds []string, filterPermissionIds []string, filterAccessUnitIds []string, justification string) *CreateAccessRequestClientModel {
	this := CreateAccessRequestClientModel{}
	this.FilterIntegrationIds = filterIntegrationIds
	this.FilterBundleIds = filterBundleIds
	this.FilterResourceTypeIds = filterResourceTypeIds
	this.FilterResourceIds = filterResourceIds
	this.FilterPermissionIds = filterPermissionIds
	this.FilterAccessUnitIds = filterAccessUnitIds
	this.Justification = justification
	return &this
}

// NewCreateAccessRequestClientModelWithDefaults instantiates a new CreateAccessRequestClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccessRequestClientModelWithDefaults() *CreateAccessRequestClientModel {
	this := CreateAccessRequestClientModel{}
	return &this
}

// GetFilterIntegrationIds returns the FilterIntegrationIds field value
func (o *CreateAccessRequestClientModel) GetFilterIntegrationIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FilterIntegrationIds
}

// GetFilterIntegrationIdsOk returns a tuple with the FilterIntegrationIds field value
// and a boolean to check if the value has been set.
func (o *CreateAccessRequestClientModel) GetFilterIntegrationIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FilterIntegrationIds, true
}

// SetFilterIntegrationIds sets field value
func (o *CreateAccessRequestClientModel) SetFilterIntegrationIds(v []string) {
	o.FilterIntegrationIds = v
}

// GetFilterBundleIds returns the FilterBundleIds field value
func (o *CreateAccessRequestClientModel) GetFilterBundleIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FilterBundleIds
}

// GetFilterBundleIdsOk returns a tuple with the FilterBundleIds field value
// and a boolean to check if the value has been set.
func (o *CreateAccessRequestClientModel) GetFilterBundleIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FilterBundleIds, true
}

// SetFilterBundleIds sets field value
func (o *CreateAccessRequestClientModel) SetFilterBundleIds(v []string) {
	o.FilterBundleIds = v
}

// GetFilterResourceTypeIds returns the FilterResourceTypeIds field value
func (o *CreateAccessRequestClientModel) GetFilterResourceTypeIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FilterResourceTypeIds
}

// GetFilterResourceTypeIdsOk returns a tuple with the FilterResourceTypeIds field value
// and a boolean to check if the value has been set.
func (o *CreateAccessRequestClientModel) GetFilterResourceTypeIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FilterResourceTypeIds, true
}

// SetFilterResourceTypeIds sets field value
func (o *CreateAccessRequestClientModel) SetFilterResourceTypeIds(v []string) {
	o.FilterResourceTypeIds = v
}

// GetFilterResourceIds returns the FilterResourceIds field value
func (o *CreateAccessRequestClientModel) GetFilterResourceIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FilterResourceIds
}

// GetFilterResourceIdsOk returns a tuple with the FilterResourceIds field value
// and a boolean to check if the value has been set.
func (o *CreateAccessRequestClientModel) GetFilterResourceIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FilterResourceIds, true
}

// SetFilterResourceIds sets field value
func (o *CreateAccessRequestClientModel) SetFilterResourceIds(v []string) {
	o.FilterResourceIds = v
}

// GetFilterPermissionIds returns the FilterPermissionIds field value
func (o *CreateAccessRequestClientModel) GetFilterPermissionIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FilterPermissionIds
}

// GetFilterPermissionIdsOk returns a tuple with the FilterPermissionIds field value
// and a boolean to check if the value has been set.
func (o *CreateAccessRequestClientModel) GetFilterPermissionIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FilterPermissionIds, true
}

// SetFilterPermissionIds sets field value
func (o *CreateAccessRequestClientModel) SetFilterPermissionIds(v []string) {
	o.FilterPermissionIds = v
}

// GetFilterAccessUnitIds returns the FilterAccessUnitIds field value
func (o *CreateAccessRequestClientModel) GetFilterAccessUnitIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FilterAccessUnitIds
}

// GetFilterAccessUnitIdsOk returns a tuple with the FilterAccessUnitIds field value
// and a boolean to check if the value has been set.
func (o *CreateAccessRequestClientModel) GetFilterAccessUnitIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FilterAccessUnitIds, true
}

// SetFilterAccessUnitIds sets field value
func (o *CreateAccessRequestClientModel) SetFilterAccessUnitIds(v []string) {
	o.FilterAccessUnitIds = v
}

// GetJustification returns the Justification field value
func (o *CreateAccessRequestClientModel) GetJustification() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Justification
}

// GetJustificationOk returns a tuple with the Justification field value
// and a boolean to check if the value has been set.
func (o *CreateAccessRequestClientModel) GetJustificationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Justification, true
}

// SetJustification sets field value
func (o *CreateAccessRequestClientModel) SetJustification(v string) {
	o.Justification = v
}

// GetDuration returns the Duration field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAccessRequestClientModel) GetDuration() int64 {
	if o == nil || IsNil(o.Duration.Get()) {
		var ret int64
		return ret
	}
	return *o.Duration.Get()
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAccessRequestClientModel) GetDurationOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Duration.Get(), o.Duration.IsSet()
}

// HasDuration returns a boolean if a field has been set.
func (o *CreateAccessRequestClientModel) HasDuration() bool {
	if o != nil && o.Duration.IsSet() {
		return true
	}

	return false
}

// SetDuration gets a reference to the given NullableInt64 and assigns it to the Duration field.
func (o *CreateAccessRequestClientModel) SetDuration(v int64) {
	o.Duration.Set(&v)
}

// SetDurationNil sets the value for Duration to be an explicit nil
func (o *CreateAccessRequestClientModel) SetDurationNil() {
	o.Duration.Set(nil)
}

// UnsetDuration ensures that no value is present for Duration, not even an explicit nil
func (o *CreateAccessRequestClientModel) UnsetDuration() {
	o.Duration.Unset()
}

func (o CreateAccessRequestClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccessRequestClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filter_integration_ids"] = o.FilterIntegrationIds
	toSerialize["filter_bundle_ids"] = o.FilterBundleIds
	toSerialize["filter_resource_type_ids"] = o.FilterResourceTypeIds
	toSerialize["filter_resource_ids"] = o.FilterResourceIds
	toSerialize["filter_permission_ids"] = o.FilterPermissionIds
	toSerialize["filter_access_unit_ids"] = o.FilterAccessUnitIds
	toSerialize["justification"] = o.Justification
	if o.Duration.IsSet() {
		toSerialize["duration"] = o.Duration.Get()
	}
	return toSerialize, nil
}

func (o *CreateAccessRequestClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filter_integration_ids",
		"filter_bundle_ids",
		"filter_resource_type_ids",
		"filter_resource_ids",
		"filter_permission_ids",
		"filter_access_unit_ids",
		"justification",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAccessRequestClientModel := _CreateAccessRequestClientModel{}

	err = json.Unmarshal(bytes, &varCreateAccessRequestClientModel)

	if err != nil {
		return err
	}

	*o = CreateAccessRequestClientModel(varCreateAccessRequestClientModel)

	return err
}

type NullableCreateAccessRequestClientModel struct {
	value *CreateAccessRequestClientModel
	isSet bool
}

func (v NullableCreateAccessRequestClientModel) Get() *CreateAccessRequestClientModel {
	return v.value
}

func (v *NullableCreateAccessRequestClientModel) Set(val *CreateAccessRequestClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccessRequestClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccessRequestClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccessRequestClientModel(val *CreateAccessRequestClientModel) *NullableCreateAccessRequestClientModel {
	return &NullableCreateAccessRequestClientModel{value: val, isSet: true}
}

func (v NullableCreateAccessRequestClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccessRequestClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
