/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
	"fmt"
)

// checks if the AccessSessionsGroupClientModelIntegration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessSessionsGroupClientModelIntegration{}

// AccessSessionsGroupClientModelIntegration struct for AccessSessionsGroupClientModelIntegration
type AccessSessionsGroupClientModelIntegration struct {
	Id              string                 `json:"id"`
	Type            string                 `json:"type"`
	TypeDisplayName string                 `json:"type_display_name"`
	Name            string                 `json:"name"`
	Icons           IconsConfigClientModel `json:"icons"`
}

type _AccessSessionsGroupClientModelIntegration AccessSessionsGroupClientModelIntegration

// NewAccessSessionsGroupClientModelIntegration instantiates a new AccessSessionsGroupClientModelIntegration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessSessionsGroupClientModelIntegration(id string, type_ string, typeDisplayName string, name string, icons IconsConfigClientModel) *AccessSessionsGroupClientModelIntegration {
	this := AccessSessionsGroupClientModelIntegration{}
	this.Id = id
	this.Type = type_
	this.TypeDisplayName = typeDisplayName
	this.Name = name
	this.Icons = icons
	return &this
}

// NewAccessSessionsGroupClientModelIntegrationWithDefaults instantiates a new AccessSessionsGroupClientModelIntegration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessSessionsGroupClientModelIntegrationWithDefaults() *AccessSessionsGroupClientModelIntegration {
	this := AccessSessionsGroupClientModelIntegration{}
	return &this
}

// GetId returns the Id field value
func (o *AccessSessionsGroupClientModelIntegration) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AccessSessionsGroupClientModelIntegration) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AccessSessionsGroupClientModelIntegration) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *AccessSessionsGroupClientModelIntegration) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AccessSessionsGroupClientModelIntegration) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AccessSessionsGroupClientModelIntegration) SetType(v string) {
	o.Type = v
}

// GetTypeDisplayName returns the TypeDisplayName field value
func (o *AccessSessionsGroupClientModelIntegration) GetTypeDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TypeDisplayName
}

// GetTypeDisplayNameOk returns a tuple with the TypeDisplayName field value
// and a boolean to check if the value has been set.
func (o *AccessSessionsGroupClientModelIntegration) GetTypeDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeDisplayName, true
}

// SetTypeDisplayName sets field value
func (o *AccessSessionsGroupClientModelIntegration) SetTypeDisplayName(v string) {
	o.TypeDisplayName = v
}

// GetName returns the Name field value
func (o *AccessSessionsGroupClientModelIntegration) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AccessSessionsGroupClientModelIntegration) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AccessSessionsGroupClientModelIntegration) SetName(v string) {
	o.Name = v
}

// GetIcons returns the Icons field value
func (o *AccessSessionsGroupClientModelIntegration) GetIcons() IconsConfigClientModel {
	if o == nil {
		var ret IconsConfigClientModel
		return ret
	}

	return o.Icons
}

// GetIconsOk returns a tuple with the Icons field value
// and a boolean to check if the value has been set.
func (o *AccessSessionsGroupClientModelIntegration) GetIconsOk() (*IconsConfigClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Icons, true
}

// SetIcons sets field value
func (o *AccessSessionsGroupClientModelIntegration) SetIcons(v IconsConfigClientModel) {
	o.Icons = v
}

func (o AccessSessionsGroupClientModelIntegration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessSessionsGroupClientModelIntegration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["type_display_name"] = o.TypeDisplayName
	toSerialize["name"] = o.Name
	toSerialize["icons"] = o.Icons
	return toSerialize, nil
}

func (o *AccessSessionsGroupClientModelIntegration) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"type_display_name",
		"name",
		"icons",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessSessionsGroupClientModelIntegration := _AccessSessionsGroupClientModelIntegration{}

	err = json.Unmarshal(bytes, &varAccessSessionsGroupClientModelIntegration)

	if err != nil {
		return err
	}

	*o = AccessSessionsGroupClientModelIntegration(varAccessSessionsGroupClientModelIntegration)

	return err
}

type NullableAccessSessionsGroupClientModelIntegration struct {
	value *AccessSessionsGroupClientModelIntegration
	isSet bool
}

func (v NullableAccessSessionsGroupClientModelIntegration) Get() *AccessSessionsGroupClientModelIntegration {
	return v.value
}

func (v *NullableAccessSessionsGroupClientModelIntegration) Set(val *AccessSessionsGroupClientModelIntegration) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessSessionsGroupClientModelIntegration) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessSessionsGroupClientModelIntegration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessSessionsGroupClientModelIntegration(val *AccessSessionsGroupClientModelIntegration) *NullableAccessSessionsGroupClientModelIntegration {
	return &NullableAccessSessionsGroupClientModelIntegration{value: val, isSet: true}
}

func (v NullableAccessSessionsGroupClientModelIntegration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessSessionsGroupClientModelIntegration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
