/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
	"fmt"
)

// checks if the ResourceClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceClientModel{}

// ResourceClientModel struct for ResourceClientModel
type ResourceClientModel struct {
	Id          string                  `json:"id"`
	Name        string                  `json:"name"`
	Path        string                  `json:"path"`
	Type        ResourceTypeClientModel `json:"type"`
	Integration IntegrationClientModel  `json:"integration"`
}

type _ResourceClientModel ResourceClientModel

// NewResourceClientModel instantiates a new ResourceClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceClientModel(id string, name string, path string, type_ ResourceTypeClientModel, integration IntegrationClientModel) *ResourceClientModel {
	this := ResourceClientModel{}
	this.Id = id
	this.Name = name
	this.Path = path
	this.Type = type_
	this.Integration = integration
	return &this
}

// NewResourceClientModelWithDefaults instantiates a new ResourceClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceClientModelWithDefaults() *ResourceClientModel {
	this := ResourceClientModel{}
	return &this
}

// GetId returns the Id field value
func (o *ResourceClientModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ResourceClientModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ResourceClientModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ResourceClientModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ResourceClientModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ResourceClientModel) SetName(v string) {
	o.Name = v
}

// GetPath returns the Path field value
func (o *ResourceClientModel) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ResourceClientModel) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ResourceClientModel) SetPath(v string) {
	o.Path = v
}

// GetType returns the Type field value
func (o *ResourceClientModel) GetType() ResourceTypeClientModel {
	if o == nil {
		var ret ResourceTypeClientModel
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ResourceClientModel) GetTypeOk() (*ResourceTypeClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ResourceClientModel) SetType(v ResourceTypeClientModel) {
	o.Type = v
}

// GetIntegration returns the Integration field value
func (o *ResourceClientModel) GetIntegration() IntegrationClientModel {
	if o == nil {
		var ret IntegrationClientModel
		return ret
	}

	return o.Integration
}

// GetIntegrationOk returns a tuple with the Integration field value
// and a boolean to check if the value has been set.
func (o *ResourceClientModel) GetIntegrationOk() (*IntegrationClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Integration, true
}

// SetIntegration sets field value
func (o *ResourceClientModel) SetIntegration(v IntegrationClientModel) {
	o.Integration = v
}

func (o ResourceClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["path"] = o.Path
	toSerialize["type"] = o.Type
	toSerialize["integration"] = o.Integration
	return toSerialize, nil
}

func (o *ResourceClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"path",
		"type",
		"integration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceClientModel := _ResourceClientModel{}

	err = json.Unmarshal(bytes, &varResourceClientModel)

	if err != nil {
		return err
	}

	*o = ResourceClientModel(varResourceClientModel)

	return err
}

type NullableResourceClientModel struct {
	value *ResourceClientModel
	isSet bool
}

func (v NullableResourceClientModel) Get() *ResourceClientModel {
	return v.value
}

func (v *NullableResourceClientModel) Set(val *ResourceClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceClientModel(val *ResourceClientModel) *NullableResourceClientModel {
	return &NullableResourceClientModel{value: val, isSet: true}
}

func (v NullableResourceClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
