/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
	"fmt"
)

// checks if the AccessSessionClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessSessionClientModel{}

// AccessSessionClientModel struct for AccessSessionClientModel
type AccessSessionClientModel struct {
	Id                string                                      `json:"id"`
	Name              string                                      `json:"name"`
	Type              SessionTypeClientModel                      `json:"type"`
	Integration       IntegrationClientModel                      `json:"integration"`
	Credentials       NullableAccessSessionClientModelCredentials `json:"credentials,omitempty"`
	ConnectionMethods []string                                    `json:"connection_methods"`
}

type _AccessSessionClientModel AccessSessionClientModel

// NewAccessSessionClientModel instantiates a new AccessSessionClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessSessionClientModel(id string, name string, type_ SessionTypeClientModel, integration IntegrationClientModel, connectionMethods []string) *AccessSessionClientModel {
	this := AccessSessionClientModel{}
	this.Id = id
	this.Name = name
	this.Type = type_
	this.Integration = integration
	this.ConnectionMethods = connectionMethods
	return &this
}

// NewAccessSessionClientModelWithDefaults instantiates a new AccessSessionClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessSessionClientModelWithDefaults() *AccessSessionClientModel {
	this := AccessSessionClientModel{}
	return &this
}

// GetId returns the Id field value
func (o *AccessSessionClientModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AccessSessionClientModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AccessSessionClientModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AccessSessionClientModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AccessSessionClientModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AccessSessionClientModel) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *AccessSessionClientModel) GetType() SessionTypeClientModel {
	if o == nil {
		var ret SessionTypeClientModel
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AccessSessionClientModel) GetTypeOk() (*SessionTypeClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AccessSessionClientModel) SetType(v SessionTypeClientModel) {
	o.Type = v
}

// GetIntegration returns the Integration field value
func (o *AccessSessionClientModel) GetIntegration() IntegrationClientModel {
	if o == nil {
		var ret IntegrationClientModel
		return ret
	}

	return o.Integration
}

// GetIntegrationOk returns a tuple with the Integration field value
// and a boolean to check if the value has been set.
func (o *AccessSessionClientModel) GetIntegrationOk() (*IntegrationClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Integration, true
}

// SetIntegration sets field value
func (o *AccessSessionClientModel) SetIntegration(v IntegrationClientModel) {
	o.Integration = v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccessSessionClientModel) GetCredentials() AccessSessionClientModelCredentials {
	if o == nil || IsNil(o.Credentials.Get()) {
		var ret AccessSessionClientModelCredentials
		return ret
	}
	return *o.Credentials.Get()
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccessSessionClientModel) GetCredentialsOk() (*AccessSessionClientModelCredentials, bool) {
	if o == nil {
		return nil, false
	}
	return o.Credentials.Get(), o.Credentials.IsSet()
}

// HasCredentials returns a boolean if a field has been set.
func (o *AccessSessionClientModel) HasCredentials() bool {
	if o != nil && o.Credentials.IsSet() {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given NullableAccessSessionClientModelCredentials and assigns it to the Credentials field.
func (o *AccessSessionClientModel) SetCredentials(v AccessSessionClientModelCredentials) {
	o.Credentials.Set(&v)
}

// SetCredentialsNil sets the value for Credentials to be an explicit nil
func (o *AccessSessionClientModel) SetCredentialsNil() {
	o.Credentials.Set(nil)
}

// UnsetCredentials ensures that no value is present for Credentials, not even an explicit nil
func (o *AccessSessionClientModel) UnsetCredentials() {
	o.Credentials.Unset()
}

// GetConnectionMethods returns the ConnectionMethods field value
func (o *AccessSessionClientModel) GetConnectionMethods() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ConnectionMethods
}

// GetConnectionMethodsOk returns a tuple with the ConnectionMethods field value
// and a boolean to check if the value has been set.
func (o *AccessSessionClientModel) GetConnectionMethodsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConnectionMethods, true
}

// SetConnectionMethods sets field value
func (o *AccessSessionClientModel) SetConnectionMethods(v []string) {
	o.ConnectionMethods = v
}

func (o AccessSessionClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessSessionClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["integration"] = o.Integration
	if o.Credentials.IsSet() {
		toSerialize["credentials"] = o.Credentials.Get()
	}
	toSerialize["connection_methods"] = o.ConnectionMethods
	return toSerialize, nil
}

func (o *AccessSessionClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"type",
		"integration",
		"connection_methods",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessSessionClientModel := _AccessSessionClientModel{}

	err = json.Unmarshal(bytes, &varAccessSessionClientModel)

	if err != nil {
		return err
	}

	*o = AccessSessionClientModel(varAccessSessionClientModel)

	return err
}

type NullableAccessSessionClientModel struct {
	value *AccessSessionClientModel
	isSet bool
}

func (v NullableAccessSessionClientModel) Get() *AccessSessionClientModel {
	return v.value
}

func (v *NullableAccessSessionClientModel) Set(val *AccessSessionClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessSessionClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessSessionClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessSessionClientModel(val *AccessSessionClientModel) *NullableAccessSessionClientModel {
	return &NullableAccessSessionClientModel{value: val, isSet: true}
}

func (v NullableAccessSessionClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessSessionClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
