/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedClientResponseModelAccessSessionClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedClientResponseModelAccessSessionClientModel{}

// PaginatedClientResponseModelAccessSessionClientModel struct for PaginatedClientResponseModelAccessSessionClientModel
type PaginatedClientResponseModelAccessSessionClientModel struct {
	Data       []AccessSessionClientModel `json:"data"`
	Pagination PaginationClientInfoModel  `json:"pagination"`
}

type _PaginatedClientResponseModelAccessSessionClientModel PaginatedClientResponseModelAccessSessionClientModel

// NewPaginatedClientResponseModelAccessSessionClientModel instantiates a new PaginatedClientResponseModelAccessSessionClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedClientResponseModelAccessSessionClientModel(data []AccessSessionClientModel, pagination PaginationClientInfoModel) *PaginatedClientResponseModelAccessSessionClientModel {
	this := PaginatedClientResponseModelAccessSessionClientModel{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewPaginatedClientResponseModelAccessSessionClientModelWithDefaults instantiates a new PaginatedClientResponseModelAccessSessionClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedClientResponseModelAccessSessionClientModelWithDefaults() *PaginatedClientResponseModelAccessSessionClientModel {
	this := PaginatedClientResponseModelAccessSessionClientModel{}
	return &this
}

// GetData returns the Data field value
func (o *PaginatedClientResponseModelAccessSessionClientModel) GetData() []AccessSessionClientModel {
	if o == nil {
		var ret []AccessSessionClientModel
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PaginatedClientResponseModelAccessSessionClientModel) GetDataOk() ([]AccessSessionClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PaginatedClientResponseModelAccessSessionClientModel) SetData(v []AccessSessionClientModel) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *PaginatedClientResponseModelAccessSessionClientModel) GetPagination() PaginationClientInfoModel {
	if o == nil {
		var ret PaginationClientInfoModel
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedClientResponseModelAccessSessionClientModel) GetPaginationOk() (*PaginationClientInfoModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedClientResponseModelAccessSessionClientModel) SetPagination(v PaginationClientInfoModel) {
	o.Pagination = v
}

func (o PaginatedClientResponseModelAccessSessionClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedClientResponseModelAccessSessionClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *PaginatedClientResponseModelAccessSessionClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedClientResponseModelAccessSessionClientModel := _PaginatedClientResponseModelAccessSessionClientModel{}

	err = json.Unmarshal(bytes, &varPaginatedClientResponseModelAccessSessionClientModel)

	if err != nil {
		return err
	}

	*o = PaginatedClientResponseModelAccessSessionClientModel(varPaginatedClientResponseModelAccessSessionClientModel)

	return err
}

type NullablePaginatedClientResponseModelAccessSessionClientModel struct {
	value *PaginatedClientResponseModelAccessSessionClientModel
	isSet bool
}

func (v NullablePaginatedClientResponseModelAccessSessionClientModel) Get() *PaginatedClientResponseModelAccessSessionClientModel {
	return v.value
}

func (v *NullablePaginatedClientResponseModelAccessSessionClientModel) Set(val *PaginatedClientResponseModelAccessSessionClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedClientResponseModelAccessSessionClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedClientResponseModelAccessSessionClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedClientResponseModelAccessSessionClientModel(val *PaginatedClientResponseModelAccessSessionClientModel) *NullablePaginatedClientResponseModelAccessSessionClientModel {
	return &NullablePaginatedClientResponseModelAccessSessionClientModel{value: val, isSet: true}
}

func (v NullablePaginatedClientResponseModelAccessSessionClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedClientResponseModelAccessSessionClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
