/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
	"fmt"
)

// checks if the ChallengeInfoClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChallengeInfoClientModel{}

// ChallengeInfoClientModel struct for ChallengeInfoClientModel
type ChallengeInfoClientModel struct {
	LogicalRelation ClientChallengeLogicalRelation `json:"logical_relation"`
	Approvers       []ChallengeApproverClientModel `json:"approvers"`
}

type _ChallengeInfoClientModel ChallengeInfoClientModel

// NewChallengeInfoClientModel instantiates a new ChallengeInfoClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChallengeInfoClientModel(logicalRelation ClientChallengeLogicalRelation, approvers []ChallengeApproverClientModel) *ChallengeInfoClientModel {
	this := ChallengeInfoClientModel{}
	this.LogicalRelation = logicalRelation
	this.Approvers = approvers
	return &this
}

// NewChallengeInfoClientModelWithDefaults instantiates a new ChallengeInfoClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChallengeInfoClientModelWithDefaults() *ChallengeInfoClientModel {
	this := ChallengeInfoClientModel{}
	return &this
}

// GetLogicalRelation returns the LogicalRelation field value
func (o *ChallengeInfoClientModel) GetLogicalRelation() ClientChallengeLogicalRelation {
	if o == nil {
		var ret ClientChallengeLogicalRelation
		return ret
	}

	return o.LogicalRelation
}

// GetLogicalRelationOk returns a tuple with the LogicalRelation field value
// and a boolean to check if the value has been set.
func (o *ChallengeInfoClientModel) GetLogicalRelationOk() (*ClientChallengeLogicalRelation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogicalRelation, true
}

// SetLogicalRelation sets field value
func (o *ChallengeInfoClientModel) SetLogicalRelation(v ClientChallengeLogicalRelation) {
	o.LogicalRelation = v
}

// GetApprovers returns the Approvers field value
func (o *ChallengeInfoClientModel) GetApprovers() []ChallengeApproverClientModel {
	if o == nil {
		var ret []ChallengeApproverClientModel
		return ret
	}

	return o.Approvers
}

// GetApproversOk returns a tuple with the Approvers field value
// and a boolean to check if the value has been set.
func (o *ChallengeInfoClientModel) GetApproversOk() ([]ChallengeApproverClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Approvers, true
}

// SetApprovers sets field value
func (o *ChallengeInfoClientModel) SetApprovers(v []ChallengeApproverClientModel) {
	o.Approvers = v
}

func (o ChallengeInfoClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChallengeInfoClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["logical_relation"] = o.LogicalRelation
	toSerialize["approvers"] = o.Approvers
	return toSerialize, nil
}

func (o *ChallengeInfoClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"logical_relation",
		"approvers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChallengeInfoClientModel := _ChallengeInfoClientModel{}

	err = json.Unmarshal(bytes, &varChallengeInfoClientModel)

	if err != nil {
		return err
	}

	*o = ChallengeInfoClientModel(varChallengeInfoClientModel)

	return err
}

type NullableChallengeInfoClientModel struct {
	value *ChallengeInfoClientModel
	isSet bool
}

func (v NullableChallengeInfoClientModel) Get() *ChallengeInfoClientModel {
	return v.value
}

func (v *NullableChallengeInfoClientModel) Set(val *ChallengeInfoClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableChallengeInfoClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableChallengeInfoClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChallengeInfoClientModel(val *ChallengeInfoClientModel) *NullableChallengeInfoClientModel {
	return &NullableChallengeInfoClientModel{value: val, isSet: true}
}

func (v NullableChallengeInfoClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChallengeInfoClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
