/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedClientResponseModelAccessUnitClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedClientResponseModelAccessUnitClientModel{}

// PaginatedClientResponseModelAccessUnitClientModel struct for PaginatedClientResponseModelAccessUnitClientModel
type PaginatedClientResponseModelAccessUnitClientModel struct {
	Data       []AccessUnitClientModel   `json:"data"`
	Pagination PaginationClientInfoModel `json:"pagination"`
}

type _PaginatedClientResponseModelAccessUnitClientModel PaginatedClientResponseModelAccessUnitClientModel

// NewPaginatedClientResponseModelAccessUnitClientModel instantiates a new PaginatedClientResponseModelAccessUnitClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedClientResponseModelAccessUnitClientModel(data []AccessUnitClientModel, pagination PaginationClientInfoModel) *PaginatedClientResponseModelAccessUnitClientModel {
	this := PaginatedClientResponseModelAccessUnitClientModel{}
	this.Data = data
	this.Pagination = pagination
	return &this
}

// NewPaginatedClientResponseModelAccessUnitClientModelWithDefaults instantiates a new PaginatedClientResponseModelAccessUnitClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedClientResponseModelAccessUnitClientModelWithDefaults() *PaginatedClientResponseModelAccessUnitClientModel {
	this := PaginatedClientResponseModelAccessUnitClientModel{}
	return &this
}

// GetData returns the Data field value
func (o *PaginatedClientResponseModelAccessUnitClientModel) GetData() []AccessUnitClientModel {
	if o == nil {
		var ret []AccessUnitClientModel
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PaginatedClientResponseModelAccessUnitClientModel) GetDataOk() ([]AccessUnitClientModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PaginatedClientResponseModelAccessUnitClientModel) SetData(v []AccessUnitClientModel) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *PaginatedClientResponseModelAccessUnitClientModel) GetPagination() PaginationClientInfoModel {
	if o == nil {
		var ret PaginationClientInfoModel
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PaginatedClientResponseModelAccessUnitClientModel) GetPaginationOk() (*PaginationClientInfoModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PaginatedClientResponseModelAccessUnitClientModel) SetPagination(v PaginationClientInfoModel) {
	o.Pagination = v
}

func (o PaginatedClientResponseModelAccessUnitClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedClientResponseModelAccessUnitClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *PaginatedClientResponseModelAccessUnitClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedClientResponseModelAccessUnitClientModel := _PaginatedClientResponseModelAccessUnitClientModel{}

	err = json.Unmarshal(bytes, &varPaginatedClientResponseModelAccessUnitClientModel)

	if err != nil {
		return err
	}

	*o = PaginatedClientResponseModelAccessUnitClientModel(varPaginatedClientResponseModelAccessUnitClientModel)

	return err
}

type NullablePaginatedClientResponseModelAccessUnitClientModel struct {
	value *PaginatedClientResponseModelAccessUnitClientModel
	isSet bool
}

func (v NullablePaginatedClientResponseModelAccessUnitClientModel) Get() *PaginatedClientResponseModelAccessUnitClientModel {
	return v.value
}

func (v *NullablePaginatedClientResponseModelAccessUnitClientModel) Set(val *PaginatedClientResponseModelAccessUnitClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedClientResponseModelAccessUnitClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedClientResponseModelAccessUnitClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedClientResponseModelAccessUnitClientModel(val *PaginatedClientResponseModelAccessUnitClientModel) *NullablePaginatedClientResponseModelAccessUnitClientModel {
	return &NullablePaginatedClientResponseModelAccessUnitClientModel{value: val, isSet: true}
}

func (v NullablePaginatedClientResponseModelAccessUnitClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedClientResponseModelAccessUnitClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
