/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
	"fmt"
)

// checks if the AccessRequestClientModelBundle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessRequestClientModelBundle{}

// AccessRequestClientModelBundle struct for AccessRequestClientModelBundle
type AccessRequestClientModelBundle struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type _AccessRequestClientModelBundle AccessRequestClientModelBundle

// NewAccessRequestClientModelBundle instantiates a new AccessRequestClientModelBundle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessRequestClientModelBundle(id string, name string) *AccessRequestClientModelBundle {
	this := AccessRequestClientModelBundle{}
	this.Id = id
	this.Name = name
	return &this
}

// NewAccessRequestClientModelBundleWithDefaults instantiates a new AccessRequestClientModelBundle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessRequestClientModelBundleWithDefaults() *AccessRequestClientModelBundle {
	this := AccessRequestClientModelBundle{}
	return &this
}

// GetId returns the Id field value
func (o *AccessRequestClientModelBundle) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AccessRequestClientModelBundle) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AccessRequestClientModelBundle) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AccessRequestClientModelBundle) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AccessRequestClientModelBundle) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AccessRequestClientModelBundle) SetName(v string) {
	o.Name = v
}

func (o AccessRequestClientModelBundle) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessRequestClientModelBundle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *AccessRequestClientModelBundle) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessRequestClientModelBundle := _AccessRequestClientModelBundle{}

	err = json.Unmarshal(bytes, &varAccessRequestClientModelBundle)

	if err != nil {
		return err
	}

	*o = AccessRequestClientModelBundle(varAccessRequestClientModelBundle)

	return err
}

type NullableAccessRequestClientModelBundle struct {
	value *AccessRequestClientModelBundle
	isSet bool
}

func (v NullableAccessRequestClientModelBundle) Get() *AccessRequestClientModelBundle {
	return v.value
}

func (v *NullableAccessRequestClientModelBundle) Set(val *AccessRequestClientModelBundle) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessRequestClientModelBundle) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessRequestClientModelBundle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessRequestClientModelBundle(val *AccessRequestClientModelBundle) *NullableAccessRequestClientModelBundle {
	return &NullableAccessRequestClientModelBundle{value: val, isSet: true}
}

func (v NullableAccessRequestClientModelBundle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessRequestClientModelBundle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
