/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apono

import (
	"encoding/json"
	"fmt"
)

// checks if the LinkClientModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkClientModel{}

// LinkClientModel struct for LinkClientModel
type LinkClientModel struct {
	Url   string `json:"url"`
	Label string `json:"label"`
}

type _LinkClientModel LinkClientModel

// NewLinkClientModel instantiates a new LinkClientModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkClientModel(url string, label string) *LinkClientModel {
	this := LinkClientModel{}
	this.Url = url
	this.Label = label
	return &this
}

// NewLinkClientModelWithDefaults instantiates a new LinkClientModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkClientModelWithDefaults() *LinkClientModel {
	this := LinkClientModel{}
	return &this
}

// GetUrl returns the Url field value
func (o *LinkClientModel) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *LinkClientModel) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *LinkClientModel) SetUrl(v string) {
	o.Url = v
}

// GetLabel returns the Label field value
func (o *LinkClientModel) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *LinkClientModel) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *LinkClientModel) SetLabel(v string) {
	o.Label = v
}

func (o LinkClientModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkClientModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["label"] = o.Label
	return toSerialize, nil
}

func (o *LinkClientModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLinkClientModel := _LinkClientModel{}

	err = json.Unmarshal(bytes, &varLinkClientModel)

	if err != nil {
		return err
	}

	*o = LinkClientModel(varLinkClientModel)

	return err
}

type NullableLinkClientModel struct {
	value *LinkClientModel
	isSet bool
}

func (v NullableLinkClientModel) Get() *LinkClientModel {
	return v.value
}

func (v *NullableLinkClientModel) Set(val *LinkClientModel) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkClientModel) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkClientModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkClientModel(val *LinkClientModel) *NullableLinkClientModel {
	return &NullableLinkClientModel{value: val, isSet: true}
}

func (v NullableLinkClientModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkClientModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
